# Generated by Django 6.0.6 on 2026-06-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhulaCode', '0004_remove_activity_completed_remove_video_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
